### ISSUE TITLE
"java.util.NoSuchElementException: No value present" when trying to pay someone from Server source (Minecraft 1.20.1 Fabric)

### ISSUE THREAD

**Issue by VickyFrenzy** [NickImpact/Impactor#7]
All I did is `/economy pay 5 someone somecurrency Server`
```
java.util.NoSuchElementException: No value present
    at java.base/java.util.Optional.get(Unknown Source)
    at net.impactdev.impactor.core.providers.ServiceProviderImplementation.provide(ServiceProviderImplementation.java:45)
    at net.impactdev.impactor.core.commands.economy.EconomyCommands.transfer(EconomyCommands.java:225)
    at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source)
    at java.base/java.lang.invoke.MethodHandle.invokeWithArguments(Unknown Source)
    at cloud.commandframework.annotations.MethodCommandExecutionHandler.execute(MethodCommandExecutionHandler.java:79)
    at cloud.commandframework.execution.CommandExecutionHandler.executeFuture(CommandExecutionHandler.java:95)
    at cloud.commandframework.execution.AsynchronousCommandExecutionCoordinator.lambda$coordinateExecution$1(AsynchronousCommandExecutionCoordinator.java:101)
    at cloud.commandframework.execution.AsynchronousCommandExecutionCoordinator.lambda$coordinateExecution$3(AsynchronousCommandExecutionCoordinator.java:131)
    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
    at java.base/java.lang.Thread.run(Unknown Source)
```
It used to work on `Impactor-Fabric-5.1.11.20.1-RC3.jar`

**Comment by ojcastillo29** [comment]
Best to utilize "eco deposit" as your server paying source

**Comment by VickyFrenzy** [comment]
> Best to utilize "eco deposit" as your server paying source

Indeed that's certainly a better way, thanks!

**Comment by NickImpact** [comment]
Good note nonetheless, looks like a service component that wasn't registered. Will push a fix for this soon.
